### ISSUE TITLE
大佬 能帮我看看是什么问题吗 我是用的你的这里的发送语音的代码

### ISSUE THREAD

**Issue by 1111mp** [Evai/RNExampleApp#10]
我遇到的问题看这个链接 https://bbs.reactnative.cn/topic/5979/我在使用react-native-audio和react-native-sound实现聊天的发送语音信息的功能时遇到了录音完之后项目会从聊天页面跳到首页的bug
还望你解答一下啊

**Comment by Evai** [comment]
对录音结束事件进行监听，然后在控制台查看打印日志进行调试。

**Comment by 1111mp** [comment]
嗯 我今天调试了很久 当我把这个hide方法注释之后就不会出现这个问题 但是我也去teaset的github上看了 这个问题还是解决不了
![image](https://user-images.githubusercontent.com/31227919/46849258-3ac48380-ce21-11e8-8597-71d28601f21b.png)
还有就是 我发录音 可以成功现在（注释掉hide代码的情况下）但是我点开听录音的时候 发现他们是同一个 这是什么原因呢

**Comment by Evai** [comment]
本地录音的path是写死的，重复录下一个语音会覆盖上一个。

**Comment by 1111mp** [comment]
嗯 重置路由的问题我已经解决了 在react-native高版本时setState的时候要格外注意
我把这两个地方改成这样就好了
![image](https://user-images.githubusercontent.com/31227919/46861943-6ad24d80-ce46-11e8-9af5-b63c14c98efb.png)
![image](https://user-images.githubusercontent.com/31227919/46861978-7aea2d00-ce46-11e8-9ced-9500d4521a17.png)

**Comment by Evai** [comment]
好的
