### ISSUE TITLE
能帮我看看这个问题吗

### ISSUE THREAD

**Issue by 1111mp** [Evai/RNExampleApp#12]
https://bbs.reactnative.cn/topic/6108/%E5%9C%A8%E4%BD%BF%E7%94%A8react-navigation%E5%AF%BC%E8%88%AA%E6%97%B6-%E5%BD%93%E5%89%8D%E9%A1%B5%E9%9D%A2%E4%B8%8D%E8%83%BDsetstate%E4%B8%8A%E4%B8%80%E4%B8%AA%E9%A1%B5%E9%9D%A2%E7%9A%84state-app%E4%BC%9A%E9%97%AA%E9%80%80-%E5%B9%B6%E6%8A%A5%E8%AD%A6%E5%91%8A
这是链接 我在react-native中文社区发起了这个问题

**Comment by Evai** [comment]
提示内存不够，最好不要直接把引用传到下个页面，传对应的方法或属性。
