### ISSUE TITLE
关于react-native-video

### ISSUE THREAD

**Issue by TopGuo** [Evai/RNExampleApp#2]
最近这个问题很困扰我，连续两个开源项目，都遇到关于video的问题，
![image](https://user-images.githubusercontent.com/30146744/44703859-c7162380-aacb-11e8-8dae-c450e9c5c503.png)
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-video'.
      > Failed to find Platform SDK with path: platforms;android-27
## 急等回复

**Comment by Evai** [comment]
执行 react-native link react-native-video 这条命令了吗？

**Comment by Evai** [comment]
https://github.com/react-native-community/react-native-video#use-android-sdk-27-by-default

**Comment by TopGuo** [comment]
这个昨天我搞了好久，这个issue不管用

**Comment by Evai** [comment]
更改下 /android/gradle/wrapper/gradle-wrapper.properties 文件
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.4-all.zip
```
然后再改下/android/build.gradle文件，下面是我的配置：
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        // Add jitpack repository (added by react-native-spinkit)
        maven { url "https://jitpack.io" }
        mavenLocal()
        jcenter()
        maven {
            url 'https://maven.google.com'
            name 'Google'
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
    project.ext {
        compileSdkVersion = 23
        buildToolsVersion = "23.0.1"

        minSdkVersion = 16
        targetSdkVersion = 22
    }
}


subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "26.0.1"
            }
        }
    }

    afterEvaluate {
        project -> if (project.hasProperty("android")) {
            android {
                compileSdkVersion 26
                buildToolsVersion '26.0.1'
            }
        }
    }
}

```
然后重新编译

**Comment by TopGuo** [comment]
👍 以前我的gradle是2.x,换成4.x的不报的react-native的错误了
![image](https://user-images.githubusercontent.com/30146744/44721523-bf22a780-aafc-11e8-86ec-205d54563041.png)
但是
👎 又出现了一个关于react-native-wechat的错误
![image](https://user-images.githubusercontent.com/30146744/44721559-de213980-aafc-11e8-9a99-304d40ad9053.png)
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-wechat'.
      > Failed to notify project evaluation listener.
         > com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V

**Comment by Evai** [comment]
@TopGuo 建议看下 react-native-wechat 的文档进行相关配置
