### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by francishero** [Evai/RNExampleApp#3]
Getting started with react native, does this project have backend too?

**Comment by Evai** [comment]
@francishero Yes, this project has a backend. But the backend code is not available, sorry.

**Comment by francishero** [comment]
is it possible to checkout how its implemented? for learning purposes  谢谢朋友

**Comment by Evai** [comment]
The back-end code is modified according to your own business, you can simulate it by using virtual data, here only the front-end code is provided, I'm sorry.

**Comment by francishero** [comment]
ok thanks
