### ISSUE TITLE
cannot find recordFilesBeforeBundleCommand.js

### ISSUE THREAD

**Issue by zhangcaochao** [Evai/RNExampleApp#4]
![image](https://user-images.githubusercontent.com/22885917/44951777-1380ab00-aea0-11e8-8ba3-eb00bfa129a9.png)

build的时候没有这个js文件导致
![image](https://user-images.githubusercontent.com/22885917/44951784-3f9c2c00-aea0-11e8-9eee-b1cb6f657c95.png)

不知道这个问题怎么解决

**Comment by Evai** [comment]
我没遇到过这种错误，你可以尝试下这里的解决方案 。 #2
