### ISSUE TITLE
请问使用 react-native-fetch-blob中的一个问题

### ISSUE THREAD

**Issue by Yunnathai** [Evai/RNExampleApp#5]
请问使用 react-native-fetch-blob中的一个问题

这个插件怎么支持iOS的后台下载呢？
一退到主页 下载进程就停止了，请问你这边是怎么处理的呢。

**Comment by Evai** [comment]
@jamninetyfive 用AppState 监听是否返回前台，然后继续下载

**Comment by Yunnathai** [comment]
你的demo中有相关的代码么，还有怎么实现暂停下载 开始断点续下载呢

**Comment by Yunnathai** [comment]
貌似这样实现不了。 打比方如果用户下载到了百分之50  退到桌面 这时候可以继续从百分之50下载？还是得重新开始下载呢。

**Comment by Evai** [comment]
@jamninetyfive 我是先查看本地是否有缓存，没有就重新下载，否则直接使用缓存中的数据。
https://github.com/Evai/RNExampleApp/blob/master/app/components/FullScreenVideo.js

**Comment by Yunnathai** [comment]
有暂停下载 的方案么。

**Comment by Yunnathai** [comment]
因为我这边最近想做一个视频下载模块，需要暂停下载 重新开始下载 下载队列等等。

**Comment by Evai** [comment]
@jamninetyfive 可以参考下这个 https://github.com/wkh237/react-native-fetch-blob/issues/193
